name: Image Analysis with Meta Llama 3.2 Vision
description: Transcription and Information Extraction from Images with Meta Llama 3.2 Vision.
author: Brandon Antone, Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-11-18"

environment_variables:
  NVIDIA_APIKEY:
    default: ""
    description: "NVIDIA API key for Llama 3.2 Usage."
    required: true
  NVIDIA_ENDPOINT: 
    default: ""
    description: "Endpoint you will use for your model"
    required: false

runtimes:
  - editor: JupyterLab
    kernel: Python 3.11 
    edition: Standard 

tasks:
  - type: run_session
    name: Install Dependencies
    script: 1_session-install-dependencies/download_requirements.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: start_application
    name: Meta Llama 3.2 Image Analysis
    subdomain: meta-llama32 
    script: 2_application/start-app.py
    short_summary: Launches Streamlit application for image analysis with Meta's Llama 3.2 LLM
    long_summary: 
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
